# Fit the model on training set

In [1]:
import os
parent_dir = "task1"
path = os.path.join(parent_dir)
print(path)
listing=os.listdir(parent_dir)

print(listing)

a =[]
paths =[]
labels =[]
for i in range(0,len(listing)):
  if listing[i]==".ipynb_checkpoints":
    print(listing[i])
    continue

  utrunk = os.listdir(parent_dir+'/'+listing[i])
  print(parent_dir+'/'+listing[i])

  for j in utrunk:
    labels.append(listing[i])    
    paths.append(parent_dir+'/'+listing[i]+"/"+j)
  a.append(utrunk)
  print(utrunk)
print(labels)
count =0
for i in paths:
  if ".ipynb" in i :
    del paths[count]
  count+1

task1
['.ipynb_checkpoints', 'abnormal', 'healthy']
.ipynb_checkpoints
task1/abnormal
['5598.png', '5599.png', '5600.png', '5601.png', '5602.png', '5603.png', '5604.png', '5605.png', '5606.png', '5607.png', '5608.png', '5609.png', '5610.png', '5611.png', '5612.png', '5613.png', '5614.png', '5615.png', '5616.png', '5617.png', '5618.png', '5619.png', '5620.png', '5621.png', '5622.png', '5623.png', '5624.png', '5625.png', '5626.png', '5627.png', '5628.png', '5629.png', '5630.png', '5631.png', '5632.png', '5633.png', '5634.png', '5635.png', '5636.png', '5637.png', '5638.png', '5639.png', '5640.png', '5641.png', '5642.png', '5643.png', '5644.png', '5645.png', '5646.png', '5647.png', '5648.png', '5649.png', '5650.png', '5651.png', '5652.png', '5653.png', '5654.png', '5655.png', '5656.png', '5657.png', '5658.png', '5659.png', '5660.png', '5661.png', '7255.png', '7256.png', '7257.png', '7258.png', '7259.png', '7260.png', '7261.png', '7262.png', '7263.png', '7264.png', '7265.png', '7266.png', '

In [2]:
im=[]
import cv2
import numpy as np
from matplotlib import pyplot as plt
for i in range(0,len(paths)):
   img = cv2.imread(paths[i],0)
   imgg=cv2.resize(img,(300,300))
   im.append(imgg)

In [3]:
x=im
y=labels
print(np.shape(x))
print(np.shape(y))

(213, 300, 300)
(213,)


In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=10)

In [5]:
x_train=np.array(x_train)
x_test=np.array(x_test)
y_train=np.array(y_train)
y_test=np.array(y_test)

print(np.array(x_train))
print('the',np.array(x_train).shape)

[[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[  0   0   0 ...   0   0 128]
  [  0   0   0 ...   0   0 128]
  [  0   0   0 ...   0   0 128]
  ...
  [  0   0   0 ...   0   0 128]
  [  0   0   0 ...   0   0 128]
  [255 255 255 ... 255 255 2

In [6]:
x_train= x_train.reshape(len(x_train),im[1].size)
x_test= x_test.reshape(len(x_test),im[1].size)
x_train=x_train.astype('float32')
x_test=x_test.astype('float32')
print(x_train.reshape(len(x_train),im[1].size))

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [  0.   0.   0. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [23]:
from sklearn import svm 
clf=svm.SVC()
clf.fit(x_train,y_train)
pred=clf.predict(x_test)

In [24]:
from  sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,pred)
accuracy

1.0

# Exporting the model

In [25]:
import pickle

In [26]:
filename='finalized svm ecg model.sav'
pickle.dump(clf,open(filename, 'wb'))

# Loading the export model

In [27]:
loaded_model=pickle.load(open(filename,'rb'))

In [28]:
result=loaded_model.score(x_test,y_test)
result

1.0

 Another method

In [21]:
import joblib

In [22]:
# joblib.dump(clf,filename)
loaded_model=joblib.load(filename)
result=loaded_model.score(x_test,y_test)
print(result)

1.0
